[server]
enableStaticServing = true
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ff2d75"
backgroundColor = "#08080c"
secondaryBackgroundColor = "#14151e"
textColor = "#f8f7ff"
font = "sans serif"
